#!/usr/bin/env python3
"""
Convert mimoagent trajectory files to SFT training format.

This script converts the traj.json files generated by mimoagent's batch.py
into JSONL format suitable for supervised fine-tuning.

Input format (mimoagent traj.json):
{
  "info": {...},
  "messages": [...],  // Standard ChatML format
  "trajectory_format": "mimoagent-1"
}

Output format (JSONL for training):
{"messages": [...]}
{"messages": [...]}
...
"""

import argparse
import json
from pathlib import Path

from tqdm import tqdm


def validate_and_normalize_message(message):
    """Validate and normalize a single message."""
    if not isinstance(message, dict):
        return None

    # Required fields must exist and be strings
    normalized = {"role": str(message.get("role", "")), "content": str(message.get("content", ""))}

    # Drop empty messages
    if not normalized["role"] or not normalized["content"]:
        return None

    return normalized


def process_message_content(message):
    """
    Process message content: if content is a list, extract text from first element.

    Args:
        message: A message dict that may have a 'content' field

    Returns:
        message: Processed message with content as string
    """
    if "content" in message and isinstance(message["content"], list):
        if len(message["content"]) > 0 and isinstance(message["content"][0], dict) and "text" in message["content"][0]:
            message = message.copy()  # Make a copy to avoid modifying original
            message["content"] = message["content"][0]["text"]
    return validate_and_normalize_message(message)


def process_single_traj(traj_file: Path) -> dict | None:
    """Process a single trajectory file."""
    try:
        with open(traj_file, encoding="utf-8") as f:
            data = json.load(f)

        # Extract messages from mimoagent format
        if "messages" not in data:
            print(f"Warning: No 'messages' field in {traj_file}")
            return None

        messages = data["messages"]
        messages = [process_message_content(message) for message in messages]
        if messages[-1]["role"] == "user":
            messages.pop()
        if not messages:
            print(f"Warning: Empty messages in {traj_file}")
            return None

        # Remove empty messages at the end (common in mimoagent)
        while messages and messages[-1]["content"].strip() == "":
            messages.pop()

        if not messages:
            print(f"Warning: All messages empty in {traj_file}")
            return None
        data.pop("messages")
        data.update({"messages": messages})
        return data

    except Exception as e:
        print(f"Error processing {traj_file}: {e}")
        return None


def process_directory(input_dir: Path, output_file: Path, pass_only: bool = False):
    """Process all traj.json files in a directory."""
    traj_files = list(input_dir.rglob("*.traj.json"))

    if not traj_files:
        print(f"No .traj.json files found in {input_dir}")
        return

    print(f"Found {len(traj_files)} trajectory files")

    processed_count = 0
    skipped_count = 0

    with open(output_file, "w", encoding="utf-8") as outfile:
        for traj_file in tqdm(traj_files, desc="Processing trajectories"):
            # Check if this is a passed instance when pass_only is True
            if pass_only:
                # Look for reward info in the traj file
                try:
                    with open(traj_file, encoding="utf-8") as f:
                        data = json.load(f)

                    # Check exit status or reward
                    info = data.get("info", {})
                    exit_status = info.get("exit_status", "")
                    reward = info.get("reward", 0)

                    # Skip if not passed (you may need to adjust these conditions)
                    if "Pass" not in exit_status and "pass" not in exit_status and reward != 1:
                        skipped_count += 1
                        continue

                except Exception:
                    # If we can't determine pass status, skip when pass_only is True
                    skipped_count += 1
                    continue

            result = process_single_traj(traj_file)
            if result:
                outfile.write(json.dumps(result, ensure_ascii=False) + "\n")
                processed_count += 1
            else:
                skipped_count += 1

    print("Processing complete:")
    print(f"  Processed: {processed_count} files")
    print(f"  Skipped: {skipped_count} files")
    print(f"  Output saved to: {output_file}")


def process_single_file(input_file: Path, output_file: Path):
    """Process a single trajectory file."""
    result = process_single_traj(input_file)
    if result:
        with open(output_file, "w", encoding="utf-8") as outfile:
            outfile.write(json.dumps(result, ensure_ascii=False) + "\n")
        print(f"Converted {input_file} -> {output_file}")
    else:
        print(f"Failed to process {input_file}")


def main():
    parser = argparse.ArgumentParser(
        description="Convert mimoagent trajectory files to SFT training format",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Convert all traj files in a directory
  python convert_mini_swe_traj_to_sft.py -i outputs/results -o training_data.jsonl
  
  # Convert only passed instances
  python convert_mini_swe_traj_to_sft.py -i outputs/results -o training_data.jsonl --pass-only
  
  # Convert a single file
  python convert_mini_swe_traj_to_sft.py -i outputs/instance1/instance1.traj.json -o instance1_training.jsonl
        """,
    )

    parser.add_argument("-i", "--input", required=True, help="Input file or directory containing .traj.json files")
    parser.add_argument("-o", "--output", required=True, help="Output JSONL file for training data")
    parser.add_argument("--pass-only", action="store_true", help="Only include trajectories from passed instances")

    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        print(f"Error: Input path {input_path} does not exist")
        return

    # Create output directory if needed
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if input_path.is_file():
        # Single file mode
        if not input_path.name.endswith(".traj.json"):
            print("Error: Input file must be a .traj.json file")
            return
        process_single_file(input_path, output_path)
    else:
        # Directory mode
        process_directory(input_path, output_path, args.pass_only)


if __name__ == "__main__":
    main()
