"""任务定义和任务适配器模块。"""

from repo_harness.tasks.adapter import LoadedTask, TaskAdapter, load_task
from repo_harness.tasks.command_policy import (
    CommandPolicy,
    CommandPolicyDecision,
    SetupCommandPolicy,
    TestCommandPolicy,
    evaluate_model_bash_command,
    is_recognized_test_command,
)
from repo_harness.tasks.environment import compute_environment_spec_hash
from repo_harness.tasks.public_environment import (
    PublicEnvironmentContext,
    PublicEnvironmentVisibilityError,
    PublicTestEntry,
    build_public_environment_context,
    project_public_environment_for_batch,
    validate_public_environment_model_visible_payload,
    write_public_environment_context_artifacts,
)
from repo_harness.tasks.schemas import (
    DecontaminationMetadata,
    EnvironmentSpec,
    FixtureRepositorySource,
    LockfileHash,
    LocalArchiveSource,
    LocalRepositorySource,
    MutationRule,
    PublicSnapshotSource,
    RealRepositorySourceFacts,
    RepoSource,
    RepoMaterializationResult,
    RunnableTask,
    SweBenchLikeEnvironmentSpec,
    SweBenchLikeTaskFacts,
    TaskAdapterFacts,
    TaskDefinition,
    TaskTimeouts,
    VerifierConfig,
    VisibilityPolicy,
)

__all__ = [
    "CommandPolicy",
    "CommandPolicyDecision",
    "DecontaminationMetadata",
    "EnvironmentSpec",
    "FixtureRepositorySource",
    "LoadedTask",
    "LockfileHash",
    "LocalArchiveSource",
    "LocalRepositorySource",
    "MutationRule",
    "PublicSnapshotSource",
    "PublicEnvironmentContext",
    "PublicEnvironmentVisibilityError",
    "PublicTestEntry",
    "RealRepositorySourceFacts",
    "RepoSource",
    "RepoMaterializationResult",
    "RunnableTask",
    "SweBenchLikeEnvironmentSpec",
    "SweBenchLikeTaskFacts",
    "TaskAdapterFacts",
    "SetupCommandPolicy",
    "TaskAdapter",
    "TaskDefinition",
    "TaskTimeouts",
    "TestCommandPolicy",
    "VerifierConfig",
    "VisibilityPolicy",
    "compute_environment_spec_hash",
    "evaluate_model_bash_command",
    "is_recognized_test_command",
    "build_public_environment_context",
    "load_task",
    "project_public_environment_for_batch",
    "validate_public_environment_model_visible_payload",
    "write_public_environment_context_artifacts",
]
