"""训练后端无关的 RepoHarness episode schema 和 LLMGateway contract。"""

from .episode import (
    AuditDiagnostic,
    BudgetConsumption,
    EpisodeBudgets,
    EpisodeStatus,
    EpisodeTaskRef,
    EpisodeVisibilityPolicy,
    PatchSummary,
    ProviderRoutePolicy,
    RepoHarnessEpisodeRequest,
    RepoHarnessEpisodeResult,
    RewardSummary,
    RunMode,
    VerifierSummary,
)
from .gateway import FakeLLMGateway, GenerationRecord, LLMGateway, LLMGatewayRequest, LLMGatewayResponse
from .timing import ResourceSummary, TimingSummary
from .training_view import (
    AuditRef,
    FormalOnlineRLSample,
    MixedLogprobBatchRejectionFixture,
    ResponseSpan,
    RolloutLimits,
    TrainingView,
    validate_formal_online_rl_batch,
    validate_training_view_for_online_rl,
)
from .visibility import (
    ALLOWED_ROUTES,
    CONTRACT_VERSION,
    PROVIDER_ROUTES,
    AuditPathAccessDeniedFixture,
    GatewayRoute,
    InferenceBackend,
    VisibilityContractError,
    default_invalid_for_online_rl,
    validate_batch_extra_fields,
    validate_gateway_extra_fields,
)

__all__ = [
    "ALLOWED_ROUTES",
    "CONTRACT_VERSION",
    "PROVIDER_ROUTES",
    "AuditDiagnostic",
    "AuditPathAccessDeniedFixture",
    "AuditRef",
    "BudgetConsumption",
    "EpisodeBudgets",
    "EpisodeStatus",
    "EpisodeTaskRef",
    "EpisodeVisibilityPolicy",
    "FakeLLMGateway",
    "FormalOnlineRLSample",
    "GatewayRoute",
    "GenerationRecord",
    "InferenceBackend",
    "LLMGateway",
    "LLMGatewayRequest",
    "LLMGatewayResponse",
    "MixedLogprobBatchRejectionFixture",
    "PatchSummary",
    "ProviderRoutePolicy",
    "RepoHarnessEpisodeRequest",
    "RepoHarnessEpisodeResult",
    "ResourceSummary",
    "ResponseSpan",
    "RewardSummary",
    "RolloutLimits",
    "RunMode",
    "TimingSummary",
    "TrainingView",
    "VerifierSummary",
    "VisibilityContractError",
    "default_invalid_for_online_rl",
    "validate_batch_extra_fields",
    "validate_formal_online_rl_batch",
    "validate_gateway_extra_fields",
    "validate_training_view_for_online_rl",
]
