from pathlib import Path

import pytest

from repo_harness.errors import TaskValidationError
from repo_harness.tasks.command_policy import (
    CommandPolicy,
    TestCommandPolicy,
    evaluate_model_bash_command,
    evaluate_model_execute_bash_command,
    is_recognized_test_command,
    validate_setup_command,
    validate_test_command,
)


def test_setup_command_policy_rejects_unallowlisted_install_command(tmp_path: Path):
    with pytest.raises(TaskValidationError, match="setup_command"):
        validate_setup_command("python -m pip install -e .", tmp_path)


def test_setup_command_policy_allows_repo_local_python_script(tmp_path: Path):
    (tmp_path / "setup_task.py").write_text("print('ok')\n", encoding="utf-8")

    decision = validate_setup_command("python setup_task.py", tmp_path)

    assert decision.decision == "allow"
    assert decision.command_category == "setup"


def test_setup_command_policy_can_validate_shape_before_archive_materialization():
    decision = validate_setup_command("python setup_task.py", None)

    assert decision.decision == "allow"
    assert decision.matched_rule == "setup_python_repo_script_shape_allowlist"


def test_test_command_policy_accepts_pytest_and_rejects_shell():
    assert validate_test_command("python -m pytest -q").decision == "allow"
    with pytest.raises(TaskValidationError, match="shell"):
        validate_test_command("pytest -q && echo hidden")


def test_model_bash_hidden_test_command_is_denied():
    policy = TestCommandPolicy(
        public_test_command="pytest -q",
        hidden_formal_verifier_command="python -m pytest tests/hidden -q",
    )

    decision = evaluate_model_bash_command(
        "python -m pytest tests/hidden -q",
        configured_test_command="pytest -q",
        test_feedback_policy="public_only",
        policy=policy,
    )

    assert decision.decision == "deny"
    assert decision.command_category == "hidden_test"


def test_model_bash_pytest_disabled_is_denied():
    decision = CommandPolicy().evaluate_model_bash(
        "pytest -q",
        configured_test_command="pytest -q",
        test_feedback_policy="disabled",
    )

    assert decision.decision == "deny"
    assert decision.matched_rule == "test_feedback_disabled_blocks_bash_test"


def test_model_bash_pytest_public_feedback_routes_to_run_tests():
    decision = CommandPolicy().evaluate_model_bash(
        "python -m pytest -q",
        configured_test_command="pytest -q",
        test_feedback_policy="structured_public_feedback",
    )

    assert decision.decision == "route_to_run_tests"
    assert decision.command_category == "public_test"


def test_tox_and_nox_are_recognized_as_test_commands_for_policy_gate():
    assert CommandPolicy().evaluate_model_bash(
        "tox",
        configured_test_command="pytest -q",
        test_feedback_policy="public_only",
    ).decision == "route_to_run_tests"
    assert CommandPolicy().evaluate_model_bash(
        "nox -s tests",
        configured_test_command="pytest -q",
        test_feedback_policy="disabled",
    ).decision == "deny"
    assert is_recognized_test_command("pytest tests/test_example.py -q", "pytest -q")


def test_unittest_is_recognized_as_test_command_for_policy_gate():
    decision = CommandPolicy().evaluate_model_bash(
        "python -m unittest tests.test_example",
        configured_test_command="pytest -q",
        test_feedback_policy="disabled",
    )

    assert decision.decision == "deny"
    assert decision.command_category == "public_test"
    assert decision.reason_code == "denied_by_final_only_feedback_policy"
    assert decision.safe_argv == ["python", "-m", "unittest", "tests.test_example"]


def test_execute_bash_policy_allows_current_worktree_diagnostics_without_false_positive():
    commands = [
        "bash -lc 'python -m pytest -q lib/matplotlib/tests/test_patches.py'",
        "git status --short",
        "git status --porcelain",
        "git diff -- src/pkg.py",
        "git diff -U3 -- src/pkg.py",
        "git grep InvalidURL",
        "git grep -e InvalidURL -- src/pkg.py",
        "git grep -C 2 InvalidURL -- src/pkg.py",
        "git ls-files",
        "git -C . status --short",
        "bash -lc 'git status --short'",
        "bash -lc 'git diff -- src/pkg.py'",
        "env bash -lc 'git status --short'",
        "command bash -lc 'git status --short'",
        "exec bash -lc 'git status --short'",
        "time pytest tests/test_example.py -q",
        "rg subprocess src",
        "rg 'runtime*' src",
        "grep 'runtime*' src/pkg.py",
        "git grep -e \"runtime*\" -- src/pkg.py",
        "pytest tests/test_subprocess.py -q",
        "rg 'exec(' src",
        "rg 'eval(' src",
        "rg '$foo' src",
        "grep '$foo' docs/public_note.txt",
        "python -c 'print(\"$literal\")'",
        "python - <<'PY'\nprint('$literal')\nPY",
        "python -m pytest -q tests/test_example.py",
        "python -m pytest -q tests/test_example.py --tb short --maxfail 1",
        "pytest tests/test_subprocess.py -q --tb=short --maxfail=1",
        "python -m unittest tests.test_example",
        "bash -lc 'python -m pytest -q lib/matplotlib/tests/test_patches.py'",
        "rg 'test_patch' docs/public_note.txt",
        "git grep 'FAIL_TO_PASS' -- docs/public_readme.md",
        "bash -lc \"git grep 'FAIL_TO_PASS' -- docs/public_readme.md\"",
        "git diff -- src/pkg.py",
        "git diff --name-only",
    ]

    for command in commands:
        decision = evaluate_model_execute_bash_command(command)
        assert decision.decision == "allow", command


@pytest.mark.parametrize(
    ("command", "reason_code"),
    [
        ("cat /repo-harness-run/task.yaml", "execute_bash_evaluator_only_marker"),
        ("cat repo-harness-run/task.yaml", "execute_bash_evaluator_only_marker"),
        ("cat gold_patch.diff", "execute_bash_evaluator_only_marker"),
        ("cat gold-patch.diff", "execute_bash_evaluator_only_marker"),
        ("cat hidden-verifier.txt", "execute_bash_evaluator_only_marker"),
        ("cat hiddenVerifier.txt", "execute_bash_evaluator_only_marker"),
        ("cat official-verifier.log", "execute_bash_evaluator_only_marker"),
        ("cat accepted_label.json", "execute_bash_evaluator_only_marker"),
        ("cat reward_metadata.json", "execute_bash_evaluator_only_marker"),
        ("cat final_verifier.json", "execute_bash_evaluator_only_marker"),
        ("cat ground_truth.json", "execute_bash_evaluator_only_marker"),
        ("cat groundTruth.json", "execute_bash_evaluator_only_marker"),
        ("cat reward_extra_info.json", "execute_bash_evaluator_only_marker"),
        ("cat rewardExtraInfo.json", "execute_bash_evaluator_only_marker"),
        ("cat evaluator_only.log", "execute_bash_evaluator_only_marker"),
        ("cat evaluator-only.log", "execute_bash_evaluator_only_marker"),
        ("cat provider_secret.txt", "execute_bash_evaluator_only_marker"),
        ("cat provider-secret.txt", "execute_bash_evaluator_only_marker"),
        ("cat secret.txt", "execute_bash_evaluator_only_marker"),
        ("git log --oneline --all", "execute_bash_git_history_or_metadata"),
        ("git -C . log --oneline --all", "execute_bash_git_history_or_metadata"),
        ("git --no-pager log --oneline --all", "execute_bash_git_history_or_metadata"),
        ("git whatchanged --oneline", "execute_bash_git_history_or_metadata"),
        ("git shortlog", "execute_bash_git_history_or_metadata"),
        ("git describe --tags", "execute_bash_git_history_or_metadata"),
        ("git rev-parse HEAD", "execute_bash_git_history_or_metadata"),
        ("git show-ref", "execute_bash_git_history_or_metadata"),
        ("git for-each-ref", "execute_bash_git_history_or_metadata"),
        ("git diff HEAD~1", "execute_bash_git_history_or_metadata"),
        ("git diff origin/main -- src/pkg.py", "execute_bash_git_history_or_metadata"),
        ("git ls-files --debug", "execute_bash_git_history_or_metadata"),
        ("git ls-files --stage", "execute_bash_git_history_or_metadata"),
        ("git ls-files --eol", "execute_bash_git_history_or_metadata"),
        ("git ls-files --unmerged", "execute_bash_git_history_or_metadata"),
        ("git ls-files --ignored --exclude-standard", "execute_bash_git_history_or_metadata"),
        ("git status --ignored", "execute_bash_git_history_or_metadata"),
        ("git status --ignored=matching", "execute_bash_git_history_or_metadata"),
        ("git status --porcelain=v2 --branch", "execute_bash_git_history_or_metadata"),
        ("git grep --cached foo", "execute_bash_git_history_or_metadata"),
        ("git grep --untracked foo", "execute_bash_git_history_or_metadata"),
        ("git grep --no-index foo", "execute_bash_git_history_or_metadata"),
        ("git grep --recurse-submodules foo", "execute_bash_git_history_or_metadata"),
        ("git grep --textconv foo", "execute_bash_git_history_or_metadata"),
        ("git grep --open-files-in-pager=less foo", "execute_bash_git_history_or_metadata"),
        ("git diff --raw", "execute_bash_git_history_or_metadata"),
        ("git diff --binary", "execute_bash_git_history_or_metadata"),
        ("git diff --full-index", "execute_bash_git_history_or_metadata"),
        ("git diff --submodule=log", "execute_bash_git_history_or_metadata"),
        ("git diff -- .env", "execute_bash_git_history_or_metadata"),
        ("git ls-files .repo_harness_env_overlay", "execute_bash_git_history_or_metadata"),
        ("git ls-files runtime_private", "execute_bash_git_history_or_metadata"),
        ("git -C runtime_private status --short", "execute_bash_git_history_or_metadata"),
        ("git --work-tree=runtime_private status --short", "execute_bash_git_history_or_metadata"),
        ("git --git-dir=.git status --short", "execute_bash_git_history_or_metadata"),
        ("python -c \"import subprocess; subprocess.run(['git', 'log'])\"", "execute_bash_git_history_or_metadata"),
        ("python -c \"import subprocess; subprocess.run(['git', '-C', '.', 'log'])\"", "execute_bash_git_history_or_metadata"),
        ("python -c \"import subprocess; subprocess.run(('git', 'log'))\"", "execute_bash_inline_process_escape"),
        ("python -c \"import subprocess; subprocess.run(['g'+'it', 'log'])\"", "execute_bash_inline_process_escape"),
        ("python -W ignore -c \"import subprocess; subprocess.run(['git', 'log'])\"", "execute_bash_git_history_or_metadata"),
        ("python3.11 -W ignore -c \"import subprocess; subprocess.run(('git', 'log'))\"", "execute_bash_inline_process_escape"),
        ("python -c \"exec('print(1)')\"", "execute_bash_inline_process_escape"),
        ("python -c \"eval('1 + 1')\"", "execute_bash_inline_process_escape"),
        ("python -c \"__import__('os').system('git log --oneline')\"", "execute_bash_inline_process_escape"),
        (
            "python -c \"getattr(__import__('os'), 'system')('git log --oneline')\"",
            "execute_bash_inline_process_escape",
        ),
        ("python -c \"__builtins__.__dict__['eval']('1+1')\"", "execute_bash_inline_process_escape"),
        ("python -c \"compile('1+1', '<x>', 'eval')\"", "execute_bash_inline_process_escape"),
        ("bash -lc 'git log --oneline --all'", "execute_bash_git_history_or_metadata"),
        ("sh -c 'git show HEAD'", "execute_bash_git_history_or_metadata"),
        ("bash -c 'git cat-file -p HEAD'", "execute_bash_git_history_or_metadata"),
        ("env bash -lc 'git log --oneline'", "execute_bash_git_history_or_metadata"),
        ("command bash -lc 'git show HEAD'", "execute_bash_git_history_or_metadata"),
        ("exec bash -lc 'git log --oneline'", "execute_bash_git_history_or_metadata"),
        (
            "bash -lc 'python -c \"import subprocess; subprocess.run([\\\"git\\\", \\\"log\\\"])\"'",
            "execute_bash_inline_process_escape",
        ),
        ("eval 'git log --oneline'", "execute_bash_shell_wrapper_unauditable"),
        ("bash -lc \"eval 'git log --oneline'\"", "execute_bash_shell_wrapper_unauditable"),
        ("bash -lc \"env bash -lc 'git log --oneline'\"", "execute_bash_git_history_or_metadata"),
        ("bash -lc $'git log --oneline'", "execute_bash_dynamic_shell_expansion"),
        ("bash -c $'git show HEAD'", "execute_bash_dynamic_shell_expansion"),
        ("rg * src", "execute_bash_dynamic_shell_expansion"),
        ("rg runtime* src", "execute_bash_dynamic_shell_expansion"),
        ("rg [.]env src", "execute_bash_dynamic_shell_expansion"),
        ("rg foo* src", "execute_bash_dynamic_shell_expansion"),
        ("grep * src/pkg.py", "execute_bash_dynamic_shell_expansion"),
        ("grep runtime* src/pkg.py", "execute_bash_dynamic_shell_expansion"),
        ("grep [.]env src/pkg.py", "execute_bash_dynamic_shell_expansion"),
        ("git grep * -- src/pkg.py", "execute_bash_dynamic_shell_expansion"),
        ("git grep runtime* -- src/pkg.py", "execute_bash_dynamic_shell_expansion"),
        ("git grep [.]env -- src/pkg.py", "execute_bash_dynamic_shell_expansion"),
        ("git grep -e runtime* -- src/pkg.py", "execute_bash_dynamic_shell_expansion"),
        ("bash -lc 'rg * src'", "execute_bash_dynamic_shell_expansion"),
        ("G=git; $G log --oneline", "execute_bash_dynamic_shell_expansion"),
        ("g=gi; t=t; $g$t log --oneline", "execute_bash_dynamic_shell_expansion"),
        ("`printf git` log --oneline", "execute_bash_dynamic_shell_expansion"),
        ("git${IFS}log --oneline", "execute_bash_dynamic_shell_expansion"),
        ("bash -lc 'G=git; $G log --oneline'", "execute_bash_dynamic_shell_expansion"),
        ("bash -lc '`printf git` log --oneline'", "execute_bash_dynamic_shell_expansion"),
        ("bash -lc 'git${IFS}log --oneline'", "execute_bash_dynamic_shell_expansion"),
        ("bash -lc 'cat <(git log --oneline)'", "execute_bash_dynamic_shell_expansion"),
        ("bash -lc 'diff <(git status --short) <(git log --oneline)'", "execute_bash_dynamic_shell_expansion"),
        ("bash -lc \"cat '$HOME/.ssh/config'\"", "execute_bash_dynamic_shell_expansion"),
        ("bash -lc \"echo '$HOME'\"", "execute_bash_dynamic_shell_expansion"),
        ("bash -lc \"python -c 'print(\\\"$HOME\\\")'\"", "execute_bash_dynamic_shell_expansion"),
        ("bash -lc \"rg '$foo' src\"", "execute_bash_dynamic_shell_expansion"),
        ("time --output=out.log pytest tests", "execute_bash_secondary_executor"),
        ("time --append --output=out.log pytest tests", "execute_bash_secondary_executor"),
        ("time --output=runtime_private/out.log pytest tests", "execute_bash_secondary_executor"),
        ("time --output=.repo_harness_env_overlay/out.log pytest tests", "execute_bash_secondary_executor"),
        ("time --format=runtime_private pytest tests", "execute_bash_secondary_executor"),
        ("time --verbose pytest tests", "execute_bash_secondary_executor"),
        ("time -v pytest tests", "execute_bash_secondary_executor"),
        ("pytest tests > out.log", "execute_bash_output_redirection"),
        ("git diff -- src/pkg.py > patch.txt", "execute_bash_output_redirection"),
        ("python -c 'print(\"ok\")' 2> err.log", "execute_bash_output_redirection"),
        ("python -c 'print(\"ok\")' &> out.log", "execute_bash_output_redirection"),
        ("printf 'git log --oneline' | sh", "execute_bash_pipe_to_interpreter"),
        ("echo 'git show HEAD' | bash", "execute_bash_pipe_to_interpreter"),
        ("cat script.sh | sh", "execute_bash_pipe_to_interpreter"),
        ("pytest tests | cat", "execute_bash_pipe_to_interpreter"),
        ("git diff -- src/pkg.py | sed s/foo/bar/", "execute_bash_pipe_to_interpreter"),
        ("rg foo src | sed s/foo/bar/", "execute_bash_pipe_to_interpreter"),
        ("python -c 'print(\"git log --oneline\")' | sh", "execute_bash_pipe_to_interpreter"),
        ("printf 'pip3 install requests' | sh", "execute_bash_pipe_to_interpreter"),
        ("printf 'cat ~/.ssh/config' | sh", "execute_bash_pipe_to_interpreter"),
        ("printf \"__import__('os').system('git log --oneline')\" | python -", "execute_bash_pipe_to_interpreter"),
        ("printf 'print(1)' | python3 -", "execute_bash_pipe_to_interpreter"),
        ("printf 'system(\"git log\")' | perl", "execute_bash_pipe_to_interpreter"),
        ("printf 'system(\"git log\")' | ruby", "execute_bash_pipe_to_interpreter"),
        ("printf 'console.log(1)' | node", "execute_bash_pipe_to_interpreter"),
        ("printf '{ system(\"git log\") }' | awk", "execute_bash_pipe_to_interpreter"),
        ("printf 'git log' | timeout 5 sh", "execute_bash_pipe_to_interpreter"),
        ("printf 'print(1)' | timeout 5 python -", "execute_bash_pipe_to_interpreter"),
        ("printf 'git log' | nice sh", "execute_bash_pipe_to_interpreter"),
        ("printf 'print(1)' | time python -", "execute_bash_pipe_to_interpreter"),
        ("printf 'git log' | command timeout 5 sh", "execute_bash_pipe_to_interpreter"),
        ("printf 'git log' | env timeout 5 sh", "execute_bash_pipe_to_interpreter"),
        ("sh < script.sh", "execute_bash_indirect_script_execution"),
        ("bash < script.sh", "execute_bash_indirect_script_execution"),
        ("python < debug.py", "execute_bash_indirect_script_execution"),
        ("python - < debug.py", "execute_bash_indirect_script_execution"),
        ("python - <<PY\nprint('$HOME')\nPY", "execute_bash_indirect_script_execution"),
        ("perl < script.pl", "execute_bash_indirect_script_execution"),
        ("node < script.js", "execute_bash_indirect_script_execution"),
        ("awk -f script.awk", "execute_bash_indirect_script_execution"),
        ("bash script.sh", "execute_bash_indirect_script_execution"),
        ("sh script.sh", "execute_bash_indirect_script_execution"),
        ("./script.sh", "execute_bash_indirect_script_execution"),
        ("source script.sh", "execute_bash_indirect_script_execution"),
        (". script.sh", "execute_bash_indirect_script_execution"),
        ("python debug.py", "execute_bash_indirect_script_execution"),
        ("python -u debug.py", "execute_bash_indirect_script_execution"),
        ("python -W ignore debug.py", "execute_bash_indirect_script_execution"),
        ("python -X dev debug.py", "execute_bash_indirect_script_execution"),
        ("python -B -W ignore debug.py", "execute_bash_indirect_script_execution"),
        ("python3 -W ignore debug.py", "execute_bash_indirect_script_execution"),
        ("python3.11 debug.py", "execute_bash_indirect_script_execution"),
        ("python3.11 -W ignore debug.py", "execute_bash_indirect_script_execution"),
        ("python -m debug_module", "execute_bash_indirect_script_execution"),
        ("bash -lc 'bash script.sh'", "execute_bash_indirect_script_execution"),
        ("bash -lc 'source script.sh'", "execute_bash_indirect_script_execution"),
        ("bash -lc 'python debug.py'", "execute_bash_indirect_script_execution"),
        ("bash -lc 'alias g=git; g log --oneline'", "execute_bash_indirect_script_execution"),
        ("alias g=git; g log --oneline", "execute_bash_indirect_script_execution"),
        ("function g { git log --oneline; }; g", "execute_bash_dynamic_shell_expansion"),
        ("g() { git log --oneline; }; g", "execute_bash_dynamic_shell_expansion"),
        ("find . -exec sh -c 'git log --oneline' \\;", "execute_bash_secondary_executor"),
        ("find . -exec bash script.sh \\;", "execute_bash_secondary_executor"),
        ("xargs sh -c 'git log --oneline'", "execute_bash_secondary_executor"),
        ("xargs -I{} sh -c 'git log --oneline'", "execute_bash_dynamic_shell_expansion"),
        ("parallel sh -c 'git log --oneline' ::: x", "execute_bash_secondary_executor"),
        ("make test", "execute_bash_secondary_executor"),
        ("make -f Makefile test", "execute_bash_secondary_executor"),
        ("npx left-pad", "execute_bash_secondary_executor"),
        ("npx --yes some-package", "execute_bash_secondary_executor"),
        ("uvx ruff", "execute_bash_secondary_executor"),
        ("stdbuf -oL pip install requests", "execute_bash_secondary_executor"),
        ("stdbuf -o0 python debug.py", "execute_bash_secondary_executor"),
        ("nohup pip install requests", "execute_bash_secondary_executor"),
        ("watch pip install requests", "execute_bash_secondary_executor"),
        ("flock lockfile pip install requests", "execute_bash_secondary_executor"),
        ("ionice -c2 pip install requests", "execute_bash_secondary_executor"),
        ("setsid pip install requests", "execute_bash_secondary_executor"),
        ("chrt -r 1 pip install requests", "execute_bash_secondary_executor"),
        ("command -p pip install requests", "execute_bash_secondary_executor"),
        ("command -p python debug.py", "execute_bash_secondary_executor"),
        ("unbuffer pip install requests", "execute_bash_secondary_executor"),
        ("script -q transcript.log -c \"pip install requests\"", "execute_bash_secondary_executor"),
        ("sudo pip install requests", "execute_bash_secondary_executor"),
        ("doas pip install requests", "execute_bash_secondary_executor"),
        ("su -c \"pip install requests\"", "execute_bash_secondary_executor"),
        ("runuser -u nobody -- pip install requests", "execute_bash_secondary_executor"),
        ("sg group -c \"pip install requests\"", "execute_bash_secondary_executor"),
        ("daemon pip install requests", "execute_bash_secondary_executor"),
        ("bash -lc 'builtin eval \"pip install requests\"'", "execute_bash_secondary_executor"),
        ("bash -lc 'builtin source script.sh'", "execute_bash_secondary_executor"),
        ("bash -lc 'builtin command -p pip install requests'", "execute_bash_secondary_executor"),
        ("bash -lc 'builtin command -p python debug.py'", "execute_bash_secondary_executor"),
        ("bash -lc 'builtin exec pip install requests'", "execute_bash_secondary_executor"),
        ("bash -lc 'builtin exec bash script.sh'", "execute_bash_secondary_executor"),
        ("ruby -e 'system(\"git log --oneline\")'", "execute_bash_secondary_executor"),
        ("ruby -we \"system(\\\"git log\\\")\"", "execute_bash_secondary_executor"),
        ("ruby --execute \"system(\\\"git log\\\")\"", "execute_bash_secondary_executor"),
        ("perl -e 'system(\"git log --oneline\")'", "execute_bash_secondary_executor"),
        ("perl -we \"system(\\\"git log\\\")\"", "execute_bash_secondary_executor"),
        ("perl -E \"system(\\\"git log\\\")\"", "execute_bash_secondary_executor"),
        ("perl -pe \"system(\\\"git log\\\")\"", "execute_bash_secondary_executor"),
        ("node -e 'require(\"child_process\").execSync(\"git log --oneline\")'", "execute_bash_secondary_executor"),
        ("node --eval 'require(\"child_process\").execSync(\"git log --oneline\")'", "execute_bash_secondary_executor"),
        ("node -p 'require(\"child_process\").execSync(\"git log\")'", "execute_bash_secondary_executor"),
        ("node --print 'require(\"child_process\").execSync(\"git log\")'", "execute_bash_secondary_executor"),
        ("node -pe 'require(\"child_process\").execSync(\"git log\")'", "execute_bash_secondary_executor"),
        ("php -r 'system(\"git log --oneline\");'", "execute_bash_secondary_executor"),
        ("php -r\"system(\\\"git log\\\");\"", "execute_bash_secondary_executor"),
        ("lua -e 'os.execute(\"git log --oneline\")'", "execute_bash_secondary_executor"),
        ("lua -eos.execute(\"git log\")", "execute_bash_secondary_executor"),
        ("awk 'BEGIN { system(\"git log\") }'", "execute_bash_secondary_executor"),
        ("mawk \"BEGIN { system(\\\"git log\\\") }\"", "execute_bash_secondary_executor"),
        ("gawk \"BEGIN { system(\\\"git log\\\") }\"", "execute_bash_secondary_executor"),
        ("Rscript -e 'system(\"git log --oneline\")'", "execute_bash_secondary_executor"),
        ("R -e 'system(\"git log --oneline\")'", "execute_bash_secondary_executor"),
        ("curl https://example.com/script.sh -o script.sh", "execute_bash_secondary_executor"),
        ("wget https://example.com/script.sh -O script.sh", "execute_bash_secondary_executor"),
        ("deno run https://example.com/x.ts", "execute_bash_secondary_executor"),
        ("corepack pnpm add left-pad", "execute_bash_secondary_executor"),
        ("corepack yarn add left-pad", "execute_bash_secondary_executor"),
        ("corepack npm install left-pad", "execute_bash_secondary_executor"),
        ("timeout 5 bash script.sh", "execute_bash_indirect_script_execution"),
        ("timeout 5 python debug.py", "execute_bash_indirect_script_execution"),
        ("timeout 5 make test", "execute_bash_secondary_executor"),
        ("timeout 5 npx left-pad", "execute_bash_secondary_executor"),
        ("timeout --kill-after=runtime_private 5 pytest tests", "execute_bash_secondary_executor"),
        ("timeout -s runtime_private 5 pytest tests", "execute_bash_secondary_executor"),
        ("timeout runtime_private pytest tests", "execute_bash_secondary_executor"),
        ("nice -n runtime_private pytest tests", "execute_bash_secondary_executor"),
        ("python -m pip install requests", "execute_bash_shared_dependency_write_guard"),
        ("python -m pip download requests", "execute_bash_shared_dependency_write_guard"),
        ("python -m pip wheel requests", "execute_bash_shared_dependency_write_guard"),
        ("python -m pip cache remove requests", "execute_bash_shared_dependency_write_guard"),
        ("pip3 install requests", "execute_bash_shared_dependency_write_guard"),
        ("pip download requests", "execute_bash_shared_dependency_write_guard"),
        ("pip wheel requests", "execute_bash_shared_dependency_write_guard"),
        ("pip cache purge", "execute_bash_shared_dependency_write_guard"),
        ("pip cache remove requests", "execute_bash_shared_dependency_write_guard"),
        ("pip-compile requirements.in", "execute_bash_shared_dependency_write_guard"),
        ("pip-sync requirements.txt", "execute_bash_shared_dependency_write_guard"),
        ("python -m pip --user install requests", "execute_bash_shared_dependency_write_guard"),
        ("timeout 5 pip install requests", "execute_bash_shared_dependency_write_guard"),
        ("timeout 5 python -m pip install requests", "execute_bash_shared_dependency_write_guard"),
        ("timeout 5 npm --prefix . install left-pad", "execute_bash_shared_dependency_write_guard"),
        ("bash -lc 'timeout 5 pip install requests'", "execute_bash_shared_dependency_write_guard"),
        ("uv add requests", "execute_bash_shared_dependency_write_guard"),
        ("uv sync", "execute_bash_shared_dependency_write_guard"),
        ("uv pip compile requirements.in", "execute_bash_shared_dependency_write_guard"),
        ("uv run --with requests pytest", "execute_bash_shared_dependency_write_guard"),
        ("uv run --with-editable . pytest", "execute_bash_shared_dependency_write_guard"),
        ("uv run --with-requirements requirements.txt pytest", "execute_bash_shared_dependency_write_guard"),
        ("uv tool run ruff", "execute_bash_shared_dependency_write_guard"),
        ("uv tool install ruff", "execute_bash_shared_dependency_write_guard"),
        ("uv tool upgrade ruff", "execute_bash_shared_dependency_write_guard"),
        ("uv tool uninstall ruff", "execute_bash_shared_dependency_write_guard"),
        ("poetry add requests", "execute_bash_shared_dependency_write_guard"),
        ("poetry install", "execute_bash_shared_dependency_write_guard"),
        ("poetry update", "execute_bash_shared_dependency_write_guard"),
        ("poetry remove requests", "execute_bash_shared_dependency_write_guard"),
        ("pipenv install requests", "execute_bash_shared_dependency_write_guard"),
        ("pipenv uninstall requests", "execute_bash_shared_dependency_write_guard"),
        ("pipenv update requests", "execute_bash_shared_dependency_write_guard"),
        ("pipx install ruff", "execute_bash_shared_dependency_write_guard"),
        ("pipx run ruff", "execute_bash_shared_dependency_write_guard"),
        ("pipx upgrade ruff", "execute_bash_shared_dependency_write_guard"),
        ("pipx uninstall ruff", "execute_bash_shared_dependency_write_guard"),
        ("pipx inject ruff requests", "execute_bash_shared_dependency_write_guard"),
        ("pdm add requests", "execute_bash_shared_dependency_write_guard"),
        ("pdm install", "execute_bash_shared_dependency_write_guard"),
        ("pdm remove requests", "execute_bash_shared_dependency_write_guard"),
        ("pdm update requests", "execute_bash_shared_dependency_write_guard"),
        ("rye add requests", "execute_bash_shared_dependency_write_guard"),
        ("rye sync", "execute_bash_shared_dependency_write_guard"),
        ("pixi add numpy", "execute_bash_shared_dependency_write_guard"),
        ("pixi install", "execute_bash_shared_dependency_write_guard"),
        ("virtualenv .venv", "execute_bash_shared_dependency_write_guard"),
        ("npm i left-pad", "execute_bash_shared_dependency_write_guard"),
        ("npm install left-pad", "execute_bash_shared_dependency_write_guard"),
        ("npm --prefix . install left-pad", "execute_bash_shared_dependency_write_guard"),
        ("npm exec left-pad", "execute_bash_shared_dependency_write_guard"),
        ("npm x left-pad", "execute_bash_shared_dependency_write_guard"),
        ("npm create vite@latest app", "execute_bash_shared_dependency_write_guard"),
        ("npm pack left-pad", "execute_bash_shared_dependency_write_guard"),
        ("npm explore left-pad -- npm install", "execute_bash_shared_dependency_write_guard"),
        ("npm run-script test", "execute_bash_shared_dependency_write_guard"),
        ("npm run test", "execute_bash_shared_dependency_write_guard"),
        ("npm test", "execute_bash_shared_dependency_write_guard"),
        ("pnpm add left-pad", "execute_bash_shared_dependency_write_guard"),
        ("pnpm --filter app add left-pad", "execute_bash_shared_dependency_write_guard"),
        ("pnpm dlx cowsay hi", "execute_bash_shared_dependency_write_guard"),
        ("pnpm create vite app", "execute_bash_shared_dependency_write_guard"),
        ("pnpm pack", "execute_bash_shared_dependency_write_guard"),
        ("pnpm test", "execute_bash_shared_dependency_write_guard"),
        ("yarn add left-pad", "execute_bash_shared_dependency_write_guard"),
        ("yarn --frozen-lockfile install", "execute_bash_shared_dependency_write_guard"),
        ("yarn --cwd . add left-pad", "execute_bash_shared_dependency_write_guard"),
        ("yarn dlx cowsay hi", "execute_bash_shared_dependency_write_guard"),
        ("yarn create vite app", "execute_bash_shared_dependency_write_guard"),
        ("yarn pack", "execute_bash_shared_dependency_write_guard"),
        ("yarn test", "execute_bash_shared_dependency_write_guard"),
        ("yarn node -e \"require('child_process').execSync('git log')\"", "execute_bash_shared_dependency_write_guard"),
        ("bunx cowsay hi", "execute_bash_shared_dependency_write_guard"),
        ("bun x cowsay hi", "execute_bash_shared_dependency_write_guard"),
        ("bun install", "execute_bash_shared_dependency_write_guard"),
        ("bun add left-pad", "execute_bash_shared_dependency_write_guard"),
        ("bun run test", "execute_bash_shared_dependency_write_guard"),
        ("conda install numpy", "execute_bash_shared_dependency_write_guard"),
        ("conda create -n x python=3.11", "execute_bash_shared_dependency_write_guard"),
        ("conda update numpy", "execute_bash_shared_dependency_write_guard"),
        ("conda remove numpy", "execute_bash_shared_dependency_write_guard"),
        ("mamba install numpy", "execute_bash_shared_dependency_write_guard"),
        ("mamba create -n x python=3.11", "execute_bash_shared_dependency_write_guard"),
        ("micromamba install numpy", "execute_bash_shared_dependency_write_guard"),
        ("micromamba update numpy", "execute_bash_shared_dependency_write_guard"),
        ("gem install rake", "execute_bash_shared_dependency_write_guard"),
        ("gem update rake", "execute_bash_shared_dependency_write_guard"),
        ("gem uninstall rake", "execute_bash_shared_dependency_write_guard"),
        ("gem build pkg.gemspec", "execute_bash_shared_dependency_write_guard"),
        ("apt-get install curl", "execute_bash_shared_dependency_write_guard"),
        ("apk add curl", "execute_bash_shared_dependency_write_guard"),
        ("yum install curl", "execute_bash_shared_dependency_write_guard"),
        ("dnf install curl", "execute_bash_shared_dependency_write_guard"),
        ("pacman -S curl", "execute_bash_shared_dependency_write_guard"),
        ("zypper install curl", "execute_bash_shared_dependency_write_guard"),
        ("brew install ripgrep", "execute_bash_shared_dependency_write_guard"),
        ("cargo add serde", "execute_bash_shared_dependency_write_guard"),
        ("cargo fetch", "execute_bash_shared_dependency_write_guard"),
        ("cargo install ripgrep", "execute_bash_shared_dependency_write_guard"),
        ("cargo update", "execute_bash_shared_dependency_write_guard"),
        ("cargo run", "execute_bash_shared_dependency_write_guard"),
        ("go get example.com/tool@latest", "execute_bash_shared_dependency_write_guard"),
        ("go install example.com/tool@latest", "execute_bash_shared_dependency_write_guard"),
        ("go mod download", "execute_bash_shared_dependency_write_guard"),
        ("go run example.com/tool@latest", "execute_bash_shared_dependency_write_guard"),
        ("bundle install", "execute_bash_shared_dependency_write_guard"),
        ("nvm install 20", "execute_bash_shared_dependency_write_guard"),
        ("asdf install python 3.11.9", "execute_bash_shared_dependency_write_guard"),
        ("pyenv install 3.11.9", "execute_bash_shared_dependency_write_guard"),
        ("rustup update", "execute_bash_shared_dependency_write_guard"),
        ("rbenv install 3.2.0", "execute_bash_shared_dependency_write_guard"),
        ("composer install", "execute_bash_shared_dependency_write_guard"),
        ("composer require monolog/monolog", "execute_bash_shared_dependency_write_guard"),
        ("pear install foo", "execute_bash_shared_dependency_write_guard"),
        ("cpan App::cpanminus", "execute_bash_shared_dependency_write_guard"),
        ("bash -lc 'pip3 install requests'", "execute_bash_shared_dependency_write_guard"),
        ("PIP_TARGET=vendor pip install requests", "execute_bash_environment_assignment_prefix"),
        ("PIP_USER=1 pip3 install requests", "execute_bash_environment_assignment_prefix"),
        ("UV_PROJECT_ENVIRONMENT=.venv uv sync", "execute_bash_environment_assignment_prefix"),
        ("npm_config_prefix=vendor npm install left-pad", "execute_bash_environment_assignment_prefix"),
        ("PYTHONPATH=. python -m pip install requests", "execute_bash_environment_assignment_prefix"),
        ("python -c \"from pathlib import Path; Path('/envs/repoA').write_text('x')\"", "execute_bash_shared_dependency_root_access"),
        ("cat /etc/passwd", "execute_bash_workspace_boundary"),
        ("cat /proc/self/environ", "execute_bash_workspace_boundary"),
        ("cat /bin/sh", "execute_bash_workspace_boundary"),
        ("cat /dev/null", "execute_bash_workspace_boundary"),
        ("cat ~/.ssh/config", "execute_bash_workspace_boundary"),
        ("cat ~root/.ssh/config", "execute_bash_workspace_boundary"),
        ("ls ~/repo", "execute_bash_workspace_boundary"),
        ("bash -lc 'cat ~/.ssh/config'", "execute_bash_workspace_boundary"),
        ("grep foo ~/.bashrc", "execute_bash_workspace_boundary"),
        ("rg foo ~/.ssh/config", "execute_bash_workspace_boundary"),
        ("grep foo ~root/.ssh/config", "execute_bash_workspace_boundary"),
        ("bash -lc 'grep foo ~/.bashrc'", "execute_bash_workspace_boundary"),
        ("true; bash script.sh", "execute_bash_control_operator"),
        ("true && bash script.sh", "execute_bash_control_operator"),
        ("true\nbash script.sh", "execute_bash_control_operator"),
        ("echo ok\npython debug.py", "execute_bash_control_operator"),
        ("echo ok\npip install requests", "execute_bash_control_operator"),
        ("true & bash script.sh", "execute_bash_control_operator"),
        ("echo ok; python debug.py", "execute_bash_control_operator"),
        ("echo ok && python -W ignore debug.py", "execute_bash_control_operator"),
        ("echo ok; source script.sh", "execute_bash_control_operator"),
        ("echo ok; pip install requests", "execute_bash_control_operator"),
        ("echo ok && pip3 install requests", "execute_bash_control_operator"),
        ("cd .. && pytest -q", "execute_bash_control_operator"),
        ("rg --files -uu", "execute_bash_unallowlisted_command"),
        ("rg --files --hidden", "execute_bash_unallowlisted_command"),
        ("rg --files --no-ignore", "execute_bash_unallowlisted_command"),
        ("rg foo -uu", "execute_bash_unallowlisted_command"),
        ("rg foo --hidden", "execute_bash_unallowlisted_command"),
        ("rg foo --no-ignore", "execute_bash_unallowlisted_command"),
        ("rg foo --no-ignore-vcs", "execute_bash_unallowlisted_command"),
        ("rg --unrestricted foo", "execute_bash_unallowlisted_command"),
        ("rg --unrestricted foo src", "execute_bash_unallowlisted_command"),
        ("rg --no-ignore-files foo", "execute_bash_unallowlisted_command"),
        ("rg --no-ignore-dot foo", "execute_bash_unallowlisted_command"),
        ("rg --ignore-file .env foo src", "execute_bash_unallowlisted_command"),
        ("rg --ignore-file=.env foo src", "execute_bash_unallowlisted_command"),
        ("rg --pre python foo src", "execute_bash_unallowlisted_command"),
        ("rg --pre=python foo src", "execute_bash_unallowlisted_command"),
        ("rg --pre-glob .env foo src", "execute_bash_unallowlisted_command"),
        ("rg --pre-glob='*.env' foo src", "execute_bash_unallowlisted_command"),
        ("rg --config .env foo src", "execute_bash_unallowlisted_command"),
        ("rg --config=.env foo src", "execute_bash_unallowlisted_command"),
        ("rg --type-add 'x:runtime_private/**' -tx foo .", "execute_bash_unallowlisted_command"),
        ("rg --type-set 'x:runtime_private/**' -tx foo .", "execute_bash_unallowlisted_command"),
        ("rg --type-add 'x:*.env' -tx foo .", "execute_bash_unallowlisted_command"),
        ("rg -tpy foo src", "execute_bash_unallowlisted_command"),
        ("rg --type py foo src", "execute_bash_unallowlisted_command"),
        ("rg -Tpy foo src", "execute_bash_unallowlisted_command"),
        ("rg foo --follow", "execute_bash_unallowlisted_command"),
        ("rg foo -g .env", "execute_bash_unallowlisted_command"),
        ("rg -g.env foo", "execute_bash_unallowlisted_command"),
        ("rg -g runtime* foo src", "execute_bash_dynamic_shell_expansion"),
        ("rg foo -f patterns.txt", "execute_bash_unallowlisted_command"),
        ("grep -R foo .", "execute_bash_unallowlisted_command"),
        ("grep -r foo .", "execute_bash_unallowlisted_command"),
        ("grep --recursive foo .", "execute_bash_unallowlisted_command"),
        ("grep -d recurse foo .", "execute_bash_unallowlisted_command"),
        ("grep --directories=recurse foo .", "execute_bash_unallowlisted_command"),
        ("grep -f patterns.txt src/pkg.py", "execute_bash_unallowlisted_command"),
        ("grep --exclude-from=.env foo .", "execute_bash_unallowlisted_command"),
        ("grep --include-from=.env foo .", "execute_bash_unallowlisted_command"),
        ("rg foo .env", "execute_bash_unallowlisted_command"),
        ("rg foo [.]env", "execute_bash_dynamic_shell_expansion"),
        ("grep foo .env", "execute_bash_unallowlisted_command"),
        ("rg foo .repo_harness_env_overlay", "execute_bash_unallowlisted_command"),
        ("rg foo .repo_harness_runtime", "execute_bash_evaluator_only_marker"),
        ("rg foo runtime_private", "execute_bash_unallowlisted_command"),
        ("grep -R foo runtime_private", "execute_bash_unallowlisted_command"),
        ("python -c 'import os; print(os.listdir(\".\"))'", "execute_bash_inline_python_visibility"),
        (
            "python -c 'from pathlib import Path; print(list(Path(\".\").rglob(\"*\")))'",
            "execute_bash_inline_python_visibility",
        ),
        ("python -c 'print(open(\".env\").read())'", "execute_bash_inline_python_visibility"),
        ("python -c 'print(open(\"runtime_private/x\").read())'", "execute_bash_inline_python_visibility"),
        ("python -c 'import sys; print(sys.path)'", "execute_bash_inline_python_visibility"),
        ("python -c 'import sys; print(sys.prefix)'", "execute_bash_inline_python_visibility"),
        ("python -c 'import site; print(site.getsitepackages())'", "execute_bash_inline_python_visibility"),
        ("python -c 'import site; print(site.PREFIXES)'", "execute_bash_inline_python_visibility"),
        ("python -c 'import sysconfig; print(sysconfig.get_paths())'", "execute_bash_inline_python_visibility"),
        ("python -c 'import pkgutil; print(list(pkgutil.iter_modules())[:10])'", "execute_bash_inline_python_visibility"),
        ("python -c 'import os; print(os.__file__)'", "execute_bash_inline_python_visibility"),
        ("python -c 'import platform; print(platform.uname())'", "execute_bash_inline_python_visibility"),
        ("python - <<'PY'\nimport os\nprint(os.listdir('.'))\nPY", "execute_bash_inline_python_visibility"),
        ("python - <<'PY'\nprint(open('.env').read())\nPY", "execute_bash_inline_python_visibility"),
        ("pytest .env", "execute_bash_unallowlisted_command"),
        ("pytest --basetemp=.repo_harness_env_overlay tests", "execute_bash_unallowlisted_command"),
        ("pytest -o cache_dir=.repo_harness_env_overlay tests", "execute_bash_unallowlisted_command"),
        ("pytest -o pythonpath=runtime_private tests", "execute_bash_unallowlisted_command"),
        ("pytest --override-ini cache_dir=.repo_harness_env_overlay tests", "execute_bash_unallowlisted_command"),
        ("pytest -p no:warnings tests", "execute_bash_unallowlisted_command"),
        ("pytest -c pytest.ini tests", "execute_bash_unallowlisted_command"),
        ("pytest --pyargs package.tests", "execute_bash_unallowlisted_command"),
        ("pytest --trace-config tests", "execute_bash_unallowlisted_command"),
        ("pytest --cache-clear tests", "execute_bash_unallowlisted_command"),
        ("pytest runtime_private.test_public", "execute_bash_unallowlisted_command"),
        ("pytest runtime-private.test_public", "execute_bash_unallowlisted_command"),
        ("pytest runtimePrivate.test_public", "execute_bash_unallowlisted_command"),
        ("pytest runtime*", "execute_bash_dynamic_shell_expansion"),
        ("pytest [.]env", "execute_bash_dynamic_shell_expansion"),
        ("python -m pytest runtime_private", "execute_bash_unallowlisted_command"),
        ("python -m pytest runtime_private.test_public", "execute_bash_unallowlisted_command"),
        ("python -m pytest runtime*", "execute_bash_dynamic_shell_expansion"),
        ("python -m pytest -o pythonpath=runtime_private tests", "execute_bash_unallowlisted_command"),
        ("python -m pytest -p no:warnings tests", "execute_bash_unallowlisted_command"),
        ("python -m unittest runtime_private.test_public", "execute_bash_unallowlisted_command"),
        ("python -m unittest discover -s runtime*", "execute_bash_dynamic_shell_expansion"),
        ("git diff -- runtime*", "execute_bash_dynamic_shell_expansion"),
        ("git grep foo -- runtime*", "execute_bash_dynamic_shell_expansion"),
        ("git -C runtime* status --short", "execute_bash_dynamic_shell_expansion"),
        ("git ls-files ':(glob).env'", "execute_bash_git_history_or_metadata"),
        ("git diff -- ':(glob).env'", "execute_bash_git_history_or_metadata"),
        ("git grep foo -- ':(glob).env'", "execute_bash_git_history_or_metadata"),
        ("git ls-files ':(top).env'", "execute_bash_git_history_or_metadata"),
        ("git diff -- ':(top).env'", "execute_bash_git_history_or_metadata"),
        ("git grep foo -- ':(top).env'", "execute_bash_git_history_or_metadata"),
        ("git ls-files ':!.env'", "execute_bash_git_history_or_metadata"),
        ("git grep \"\" HEAD:src/repo_harness/tasks/command_policy.py", "execute_bash_git_history_or_metadata"),
        ("git grep foo HEAD:tests/hidden/test_api.py", "execute_bash_git_history_or_metadata"),
        ("git grep foo @:src/pkg.py", "execute_bash_git_history_or_metadata"),
        ("git grep foo main:src/pkg.py", "execute_bash_git_history_or_metadata"),
        (
            "git diff HEAD:src/repo_harness/tasks/command_policy.py -- src/repo_harness/tasks/command_policy.py",
            "execute_bash_git_history_or_metadata",
        ),
        ("git diff @:src/pkg.py -- src/pkg.py", "execute_bash_git_history_or_metadata"),
        ("git diff main:src/pkg.py -- src/pkg.py", "execute_bash_git_history_or_metadata"),
        ("cat README.md", "execute_bash_unallowlisted_command"),
    ],
)
def test_execute_bash_policy_rejects_hidden_history_and_dependency_writes(command: str, reason_code: str):
    decision = evaluate_model_execute_bash_command(
        command,
        shared_dependency_environment_roots=["/envs/repoA"],
    )

    assert decision.decision == "deny"
    assert decision.reason_code == reason_code


def test_execute_bash_policy_fails_closed_when_shared_environment_roots_missing():
    decision = evaluate_model_execute_bash_command(
        "python -c \"print('ok')\"",
        shared_dependency_environment_expected=True,
        shared_dependency_environment_roots=None,
    )

    assert decision.decision == "deny"
    assert decision.reason_code == "execute_bash_shared_dependency_roots_missing"
